Comments = {
    "brain_thresh":"# Brain/background threshold, %\n",
    "critical_z":"# Critical z for design efficiency calculation\n",
    "noise":"# Noise level\n",
    "noisear":"# Noise AR(1)\n",
    "newdir_yn":"# 0 : Overwrite original post-stats results\n# 1 : Copy original FEAT directory for new Contrasts, Thresholding, Rendering\n",
    "sscleanup_yn":"# Cleanup first-level standard-space images\n",
    "ndelete":"# Delete volumes\n",
    "tr":"# TR(s)\n",
    "paradigm_hp":"# High pass filter cutoff\n",
    "mc":"# Motion correction\n# 0 : None\n# 1 : MCFLIRT\n",
    "regunwarp_yn":"# B1 unwarping\n",
    "alternateReference_yn":"# Alternate reference\n",
    "dwell":"# EPI dwell time (ms)\n",
    "te":"# EPI TE (ms)\n",
    "signallossthresh":"# % Signal loss threshold\n",
    "unwarp_dir":"# Unwarp direction\n",
    "st":"# Slice timing correction\n# 0 : None\n# 1 : Regular up (0, 1, 2, 3, ...)\n# 2 : Regular down\n# 3 : Use slice order file\n# 4 : Use slice timings file\n# 5 : Interleaved (0, 2, 4 ... 1, 3, 5 ... )\n",
    "bet_yn":"# BET brain extraction\n",
    "smooth":"# Spatial smoothing FWHM (mm)\n",
    "norm_yn":"# Intensity normalization\n",
    "perfsub_yn":"# Perfusion subtraction\n",
    "tagfirst":"# Perfusion tag/control order\n",
    "temphp_yn":"# Highpass temporal filtering\n",
    "templp_yn":"# Lowpass temporal filtering\n",
    "melodic_yn":"# MELODIC ICA data exploration\n",
    "prewhiten_yn":"# Carry out prewhitening?\n",
    "motionevs":"# Add motion parameters to model\n# 0 : No\n# 1 : Yes\n",
    "confoundevs":"# General confound matrix (any number of EVs)\n",
    "robust_yn":"# Robust outlier detection in FLAME\n",
    "mixed_yn":"# Higher-level modelling\n# 3 : Fixed effects\n# 0 : Mixed Effects: Simple OLS\n# 2 : Mixed Effects: FLAME 1\n# 1 : Mixed Effects: FLAME 1+2\n",
    "randomisePermutations":"# Higher-level permutations\n",
    "thresh":"# Thresholding\n# 0 : None\n# 1 : Uncorrected\n# 2 : Voxel\n# 3 : Cluster\n",
    "prob_thresh":"# P threshold\n",
    "z_thresh":"# Z threshold\n",
    "zdisplay":"# Z min/max for colour rendering\n# 0 : Use actual Z min/max\n# 1 : Use preset Z min/max\n",
    "zmin":"# Z min in colour rendering\n",
    "zmax":"# Z max in colour rendering\n",
    "rendertype":"# Colour rendering type\n# 0 : Solid blobs\n# 1 : Transparent blobs\n",
    "bgimage":"# Background image for higher-level stats overlays\n# 1 : Mean highres\n# 2 : First highres\n# 3 : Mean functional\n# 4 : First functional\n# 5 : Standard space template\n",
    "tsplot_yn":"# Create time series plots\n",
    "reginitial_highres_search":"# Search space for registration to initial structural\n# 0   : No search\n# 90  : Normal search\n# 180 : Full search\n",
    "reginitial_highres_dof":"# Degrees of Freedom for registration to initial structural\n# options: 3/6/7/9/12\n",
    "reghighres_search":"# Search space for registration to main structural\n",
    "reghighres_dof":"# Degrees of Freedom for registration to main structural\n",
    "regstandard":"# Standard image\n",
    "regstandard_search":"# Search space for registration to standard space\n",
    "regstandard_dof":"# Degrees of Freedom for registration to standard space\n",
    "regstandard_nonlinear_yn":"# Do nonlinear registration from structural to standard space?\n",
    "regstandard_nonlinear_warpres":"# Control nonlinear warp field resolution\n",
}